// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state7 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond389_i_reg_2494;
reg   [0:0] or_cond_i_i_reg_2503;
reg   [0:0] icmp_reg_2447;
reg   [0:0] tmp_1_reg_2438;
reg    p_src_data_stream_1_V_blk_n;
reg    p_src_data_stream_2_V_blk_n;
reg    p_dst_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] or_cond_i_reg_2543;
reg   [0:0] or_cond_i_reg_2543_pp0_iter1_reg;
reg    p_dst_data_stream_1_V_blk_n;
reg    p_dst_data_stream_2_V_blk_n;
reg   [10:0] t_V_2_reg_516;
wire   [1:0] tmp_6_fu_527_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond390_i_fu_543_p2;
wire    ap_CS_fsm_state3;
wire   [9:0] i_V_fu_549_p2;
reg   [9:0] i_V_reg_2433;
wire   [0:0] tmp_1_fu_555_p2;
wire   [0:0] tmp_72_0_0_not_fu_561_p2;
reg   [0:0] tmp_72_0_0_not_reg_2442;
wire   [0:0] icmp_fu_577_p2;
wire   [0:0] tmp_9_fu_583_p2;
reg   [0:0] tmp_9_reg_2452;
wire   [0:0] tmp_116_0_1_fu_589_p2;
reg   [0:0] tmp_116_0_1_reg_2456;
wire   [0:0] tmp_2_fu_595_p2;
reg   [0:0] tmp_2_reg_2460;
wire   [1:0] row_assign_9_0_0_t_fu_749_p2;
reg   [1:0] row_assign_9_0_0_t_reg_2473;
wire   [1:0] row_assign_9_0_1_t_fu_787_p2;
reg   [1:0] row_assign_9_0_1_t_reg_2480;
wire   [1:0] row_assign_9_0_2_t_fu_825_p2;
reg   [1:0] row_assign_9_0_2_t_reg_2487;
wire   [0:0] exitcond389_i_fu_835_p2;
wire    ap_block_state4_pp0_stage0_iter0;
reg    ap_predicate_op210_read_state5;
reg    ap_predicate_op222_read_state5;
reg    ap_predicate_op274_read_state5;
reg    ap_predicate_op286_read_state5;
reg    ap_predicate_op335_read_state5;
reg    ap_predicate_op344_read_state5;
reg    ap_block_state5_pp0_stage0_iter1;
reg    ap_block_state6_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [10:0] j_V_fu_841_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_fu_889_p2;
wire   [1:0] tmp_50_fu_949_p1;
reg   [1:0] tmp_50_reg_2507;
wire   [0:0] brmerge_fu_953_p2;
reg   [0:0] brmerge_reg_2512;
reg   [10:0] k_buf_0_val_3_addr_reg_2525;
reg   [10:0] k_buf_0_val_4_addr_reg_2531;
reg   [10:0] k_buf_0_val_5_addr_reg_2537;
wire   [0:0] or_cond_i_fu_971_p2;
reg   [10:0] k_buf_1_val_3_addr_reg_2547;
reg   [10:0] k_buf_1_val_4_addr_reg_2553;
reg   [10:0] k_buf_1_val_5_addr_reg_2559;
reg   [10:0] k_buf_2_val_3_addr_reg_2565;
reg   [10:0] k_buf_2_val_4_addr_reg_2571;
reg   [10:0] k_buf_2_val_5_addr_reg_2577;
wire   [7:0] src_kernel_win_0_va_7_fu_1133_p3;
reg   [7:0] src_kernel_win_0_va_7_reg_2583;
wire   [10:0] tmp2_fu_1237_p2;
reg   [10:0] tmp2_reg_2589;
wire   [9:0] tmp4_fu_1243_p2;
reg   [9:0] tmp4_reg_2594;
wire   [7:0] tmp5_fu_1249_p2;
reg   [7:0] tmp5_reg_2599;
wire   [7:0] tmp7_fu_1255_p2;
reg   [7:0] tmp7_reg_2604;
wire   [7:0] src_kernel_win_1_va_7_fu_1404_p3;
reg   [7:0] src_kernel_win_1_va_7_reg_2609;
wire   [10:0] tmp10_fu_1508_p2;
reg   [10:0] tmp10_reg_2615;
wire   [9:0] tmp12_fu_1514_p2;
reg   [9:0] tmp12_reg_2620;
wire   [7:0] tmp13_fu_1520_p2;
reg   [7:0] tmp13_reg_2625;
wire   [7:0] tmp15_fu_1526_p2;
reg   [7:0] tmp15_reg_2630;
wire   [7:0] src_kernel_win_2_va_10_fu_1657_p3;
reg   [7:0] src_kernel_win_2_va_10_reg_2635;
wire   [10:0] tmp18_fu_1761_p2;
reg   [10:0] tmp18_reg_2641;
wire   [9:0] tmp20_fu_1767_p2;
reg   [9:0] tmp20_reg_2646;
wire   [7:0] tmp21_fu_1773_p2;
reg   [7:0] tmp21_reg_2651;
wire   [7:0] tmp23_fu_1779_p2;
reg   [7:0] tmp23_reg_2656;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter1_state5;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
wire   [10:0] k_buf_1_val_3_address0;
reg    k_buf_1_val_3_ce0;
wire   [7:0] k_buf_1_val_3_q0;
reg    k_buf_1_val_3_ce1;
reg    k_buf_1_val_3_we1;
wire   [10:0] k_buf_1_val_4_address0;
reg    k_buf_1_val_4_ce0;
wire   [7:0] k_buf_1_val_4_q0;
reg    k_buf_1_val_4_ce1;
reg    k_buf_1_val_4_we1;
reg   [7:0] k_buf_1_val_4_d1;
wire   [10:0] k_buf_1_val_5_address0;
reg    k_buf_1_val_5_ce0;
wire   [7:0] k_buf_1_val_5_q0;
reg    k_buf_1_val_5_ce1;
reg    k_buf_1_val_5_we1;
reg   [7:0] k_buf_1_val_5_d1;
wire   [10:0] k_buf_2_val_3_address0;
reg    k_buf_2_val_3_ce0;
wire   [7:0] k_buf_2_val_3_q0;
reg    k_buf_2_val_3_ce1;
reg    k_buf_2_val_3_we1;
wire   [10:0] k_buf_2_val_4_address0;
reg    k_buf_2_val_4_ce0;
wire   [7:0] k_buf_2_val_4_q0;
reg    k_buf_2_val_4_ce1;
reg    k_buf_2_val_4_we1;
reg   [7:0] k_buf_2_val_4_d1;
wire   [10:0] k_buf_2_val_5_address0;
reg    k_buf_2_val_5_ce0;
wire   [7:0] k_buf_2_val_5_q0;
reg    k_buf_2_val_5_ce1;
reg    k_buf_2_val_5_we1;
reg   [7:0] k_buf_2_val_5_d1;
reg   [1:0] tmp_5_reg_494;
wire   [0:0] tmp_7_fu_533_p2;
reg   [9:0] t_V_reg_505;
wire    ap_CS_fsm_state7;
wire   [63:0] tmp_25_fu_958_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_170;
wire   [7:0] src_kernel_win_0_va_6_fu_1115_p3;
reg   [7:0] src_kernel_win_0_va_1_fu_174;
reg   [7:0] src_kernel_win_0_va_2_fu_178;
reg   [7:0] src_kernel_win_0_va_3_fu_182;
reg   [7:0] src_kernel_win_0_va_4_fu_186;
wire   [7:0] src_kernel_win_0_va_8_fu_1151_p3;
reg   [7:0] src_kernel_win_0_va_5_fu_190;
reg   [7:0] src_kernel_win_1_va_fu_194;
wire   [7:0] src_kernel_win_1_va_6_fu_1386_p3;
reg   [7:0] src_kernel_win_1_va_1_fu_198;
reg   [7:0] src_kernel_win_1_va_2_fu_202;
reg   [7:0] src_kernel_win_1_va_3_fu_206;
reg   [7:0] src_kernel_win_1_va_4_fu_210;
wire   [7:0] src_kernel_win_1_va_8_fu_1422_p3;
reg   [7:0] src_kernel_win_1_va_5_fu_214;
reg   [7:0] src_kernel_win_2_va_fu_218;
wire   [7:0] src_kernel_win_2_va_9_fu_1639_p3;
reg   [7:0] src_kernel_win_2_va_1_fu_222;
reg   [7:0] src_kernel_win_2_va_2_fu_226;
reg   [7:0] src_kernel_win_2_va_3_fu_230;
reg   [7:0] src_kernel_win_2_va_4_fu_234;
wire   [7:0] src_kernel_win_2_va_11_fu_1675_p3;
reg   [7:0] src_kernel_win_2_va_5_fu_238;
reg   [7:0] right_border_buf_0_s_fu_242;
wire   [7:0] col_buf_0_val_0_0_fu_1020_p3;
reg   [7:0] right_border_buf_0_1_fu_246;
reg   [7:0] right_border_buf_2_s_fu_250;
reg   [7:0] right_border_buf_0_2_fu_254;
wire   [7:0] col_buf_0_val_1_0_fu_1039_p3;
reg   [7:0] right_border_buf_0_3_fu_258;
reg   [7:0] right_border_buf_2_1_fu_262;
wire   [7:0] col_buf_2_val_2_0_fu_1591_p3;
reg   [7:0] right_border_buf_0_4_fu_266;
wire   [7:0] col_buf_0_val_2_0_fu_1058_p3;
reg   [7:0] right_border_buf_0_5_fu_270;
reg   [7:0] right_border_buf_2_2_fu_274;
reg   [7:0] right_border_buf_1_s_fu_278;
wire   [7:0] col_buf_1_val_0_0_fu_1291_p3;
reg   [7:0] right_border_buf_1_1_fu_282;
reg   [7:0] right_border_buf_2_3_fu_286;
wire   [7:0] col_buf_2_val_1_0_fu_1572_p3;
reg   [7:0] right_border_buf_1_2_fu_290;
wire   [7:0] col_buf_1_val_1_0_fu_1310_p3;
reg   [7:0] right_border_buf_1_3_fu_294;
reg   [7:0] right_border_buf_2_4_fu_298;
reg   [7:0] right_border_buf_1_4_fu_302;
wire   [7:0] col_buf_1_val_2_0_fu_1329_p3;
reg   [7:0] right_border_buf_1_5_fu_306;
reg   [7:0] right_border_buf_2_5_fu_310;
wire   [7:0] col_buf_2_val_0_0_fu_1553_p3;
wire   [8:0] tmp_fu_567_p4;
wire   [10:0] t_V_cast_fu_539_p1;
wire   [1:0] tmp_8_fu_601_p1;
wire   [10:0] tmp_3_fu_605_p2;
wire   [0:0] tmp_10_fu_617_p3;
wire   [0:0] tmp_4_fu_631_p2;
wire   [0:0] rev_fu_625_p2;
wire   [0:0] tmp_11_fu_643_p3;
wire   [10:0] p_assign_7_fu_651_p2;
wire   [10:0] p_p2_i426_i_fu_657_p3;
wire   [1:0] tmp_12_fu_665_p1;
wire   [10:0] p_assign_6_0_1_fu_681_p2;
wire   [10:0] p_assign_6_0_2_fu_707_p2;
wire   [0:0] tmp_13_fu_669_p2;
wire   [1:0] p_assign_8_fu_675_p2;
wire   [0:0] or_cond_i425_i_fu_637_p2;
wire   [1:0] tmp_140_cast_fu_611_p2;
wire   [1:0] p_p2_i426_i_0_p_assig_fu_733_p3;
wire   [1:0] y_1_fu_741_p3;
wire   [1:0] tmp_17_fu_703_p1;
wire   [0:0] tmp_15_fu_695_p3;
wire   [1:0] tmp_24_fu_761_p2;
wire   [1:0] tmp_30_fu_767_p1;
wire   [0:0] tmp_14_fu_687_p3;
wire   [1:0] tmp_31_fu_771_p3;
wire   [1:0] tmp_16_fu_755_p2;
wire   [1:0] tmp_32_fu_779_p3;
wire   [1:0] tmp_22_fu_729_p1;
wire   [0:0] tmp_20_fu_721_p3;
wire   [1:0] tmp_35_fu_799_p2;
wire   [1:0] tmp_38_fu_805_p1;
wire   [0:0] tmp_19_fu_713_p3;
wire   [1:0] tmp_39_fu_809_p3;
wire   [1:0] tmp_34_fu_793_p2;
wire   [1:0] tmp_36_fu_817_p3;
wire   [9:0] tmp_40_fu_847_p4;
wire   [11:0] t_V_2_cast_fu_831_p1;
wire   [11:0] ImagLoc_x_fu_863_p2;
wire   [0:0] tmp_41_fu_869_p3;
wire   [0:0] tmp_21_fu_883_p2;
wire   [0:0] rev1_fu_877_p2;
wire   [0:0] tmp_43_fu_895_p3;
wire   [11:0] p_assign_1_fu_903_p2;
wire   [11:0] p_p2_i_i_fu_909_p3;
wire   [0:0] tmp_23_fu_917_p2;
wire   [11:0] p_assign_2_fu_923_p2;
wire   [11:0] p_p2_i_i_p_assign_2_fu_929_p3;
wire  signed [11:0] x_fu_937_p3;
wire  signed [31:0] x_cast_fu_945_p1;
wire   [0:0] icmp1_fu_857_p2;
wire   [1:0] col_assign_2_0_t_fu_1003_p2;
wire   [7:0] tmp_26_fu_1008_p5;
wire   [7:0] tmp_27_fu_1027_p5;
wire   [7:0] tmp_28_fu_1046_p5;
wire   [7:0] tmp_29_fu_1104_p5;
wire   [7:0] tmp_33_fu_1122_p5;
wire   [7:0] tmp_37_fu_1140_p5;
wire   [8:0] tmp_160_0_0_2_cast_fu_1171_p1;
wire   [8:0] OP1_V_0_0_cast_fu_1167_p1;
wire  signed [8:0] p_Val2_10_0_0_2_fu_1175_p2;
wire   [8:0] p_shl_fu_1185_p3;
wire   [9:0] p_shl_cast_fu_1193_p1;
wire  signed [9:0] r_V_7_0_1_fu_1197_p2;
wire   [8:0] OP1_V_0_2_cast_fu_1215_p1;
wire  signed [8:0] r_V_7_0_2_fu_1219_p2;
wire  signed [10:0] tmp_160_0_2_cast_fu_1225_p1;
wire  signed [10:0] tmp_160_0_1_cast_fu_1203_p1;
wire   [9:0] tmp_160_0_2_2_cast_c_fu_1233_p1;
wire  signed [9:0] p_Val2_10_0_0_2_ca_fu_1181_p1;
wire   [7:0] tmp_55_fu_1211_p1;
wire   [7:0] tmp_53_fu_1207_p1;
wire   [7:0] tmp_63_fu_1229_p1;
wire   [7:0] tmp_44_fu_1279_p5;
wire   [7:0] tmp_45_fu_1298_p5;
wire   [7:0] tmp_46_fu_1317_p5;
wire   [7:0] tmp_47_fu_1375_p5;
wire   [7:0] tmp_48_fu_1393_p5;
wire   [7:0] tmp_49_fu_1411_p5;
wire   [8:0] tmp_160_1_0_2_cast_fu_1442_p1;
wire   [8:0] OP1_V_1_0_cast_fu_1438_p1;
wire  signed [8:0] p_Val2_10_1_0_2_fu_1446_p2;
wire   [8:0] p_shl1_fu_1456_p3;
wire   [9:0] p_shl1_cast_fu_1464_p1;
wire  signed [9:0] r_V_7_1_1_fu_1468_p2;
wire   [8:0] OP1_V_1_2_cast_fu_1486_p1;
wire  signed [8:0] r_V_7_1_2_fu_1490_p2;
wire  signed [10:0] tmp_160_1_2_cast_fu_1496_p1;
wire  signed [10:0] tmp_160_1_1_cast_fu_1474_p1;
wire   [9:0] tmp_160_1_2_2_cast_c_fu_1504_p1;
wire  signed [9:0] p_Val2_10_1_0_2_ca_fu_1452_p1;
wire   [7:0] tmp_70_fu_1482_p1;
wire   [7:0] tmp_69_fu_1478_p1;
wire   [7:0] tmp_72_fu_1500_p1;
wire   [7:0] tmp_56_fu_1541_p5;
wire   [7:0] tmp_57_fu_1560_p5;
wire   [7:0] tmp_58_fu_1579_p5;
wire   [7:0] tmp_59_fu_1628_p5;
wire   [7:0] tmp_60_fu_1646_p5;
wire   [7:0] tmp_61_fu_1664_p5;
wire   [8:0] tmp_160_2_0_2_cast_fu_1695_p1;
wire   [8:0] OP1_V_2_0_cast_fu_1691_p1;
wire  signed [8:0] p_Val2_10_2_0_2_fu_1699_p2;
wire   [8:0] p_shl2_fu_1709_p3;
wire   [9:0] p_shl2_cast_fu_1717_p1;
wire  signed [9:0] r_V_7_2_1_fu_1721_p2;
wire   [8:0] OP1_V_2_2_cast_fu_1739_p1;
wire  signed [8:0] r_V_7_2_2_fu_1743_p2;
wire  signed [10:0] tmp_160_2_2_cast_fu_1749_p1;
wire  signed [10:0] tmp_160_2_1_cast_fu_1727_p1;
wire   [9:0] tmp_160_2_2_2_cast_c_fu_1757_p1;
wire  signed [9:0] p_Val2_10_2_0_2_ca_fu_1705_p1;
wire   [7:0] tmp_78_fu_1735_p1;
wire   [7:0] tmp_77_fu_1731_p1;
wire   [7:0] tmp_80_fu_1753_p1;
wire   [8:0] r_V_7_0_1_2_fu_1902_p3;
wire   [10:0] tmp_160_0_1_cast_64_fu_1909_p1;
wire  signed [10:0] tmp4_cast_fu_1918_p1;
wire   [10:0] tmp3_fu_1921_p2;
wire   [10:0] p_Val2_2_fu_1927_p2;
wire   [7:0] tmp_62_fu_1913_p2;
wire   [7:0] tmp6_fu_1940_p2;
wire   [0:0] isneg_fu_1932_p3;
wire   [2:0] tmp_42_fu_1950_p4;
wire   [0:0] not_i_i_i_fu_1966_p2;
wire   [0:0] tmp_i_i_fu_1960_p2;
wire   [0:0] overflow_fu_1972_p2;
wire   [0:0] tmp_i_i_65_fu_1986_p2;
wire   [7:0] p_mux_i_i_cast_fu_1978_p3;
wire   [7:0] p_Val2_1_fu_1945_p2;
wire   [8:0] r_V_7_1_1_2_fu_2001_p3;
wire   [10:0] tmp_160_1_1_cast_66_fu_2008_p1;
wire  signed [10:0] tmp12_cast_fu_2017_p1;
wire   [10:0] tmp11_fu_2020_p2;
wire   [10:0] p_Val2_5_fu_2026_p2;
wire   [7:0] tmp_71_fu_2012_p2;
wire   [7:0] tmp14_fu_2039_p2;
wire   [0:0] isneg_1_fu_2031_p3;
wire   [2:0] tmp_54_fu_2049_p4;
wire   [0:0] not_i_i_i1_fu_2065_p2;
wire   [0:0] tmp_i_i1_fu_2059_p2;
wire   [0:0] overflow_1_fu_2071_p2;
wire   [0:0] tmp_i_i1_67_fu_2085_p2;
wire   [7:0] p_mux_i_i30_cast_fu_2077_p3;
wire   [7:0] p_Val2_3_fu_2044_p2;
wire   [8:0] r_V_7_2_1_2_fu_2100_p3;
wire   [10:0] tmp_160_2_1_cast_68_fu_2107_p1;
wire  signed [10:0] tmp20_cast_fu_2116_p1;
wire   [10:0] tmp19_fu_2119_p2;
wire   [10:0] p_Val2_s_fu_2125_p2;
wire   [7:0] tmp_79_fu_2111_p2;
wire   [7:0] tmp22_fu_2138_p2;
wire   [0:0] isneg_2_fu_2130_p3;
wire   [2:0] tmp_64_fu_2148_p4;
wire   [0:0] not_i_i_i2_fu_2164_p2;
wire   [0:0] tmp_i_i2_fu_2158_p2;
wire   [0:0] overflow_2_fu_2170_p2;
wire   [0:0] tmp_i_i2_69_fu_2184_p2;
wire   [7:0] p_mux_i_i39_cast_fu_2176_p3;
wire   [7:0] p_Val2_6_fu_2143_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_553;
reg    ap_condition_62;
reg    ap_condition_547;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_addr_reg_2525),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_0_V_dout)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_addr_reg_2531),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_addr_reg_2537),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_1_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_3_address0),
    .ce0(k_buf_1_val_3_ce0),
    .q0(k_buf_1_val_3_q0),
    .address1(k_buf_1_val_3_addr_reg_2547),
    .ce1(k_buf_1_val_3_ce1),
    .we1(k_buf_1_val_3_we1),
    .d1(p_src_data_stream_1_V_dout)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_1_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_4_address0),
    .ce0(k_buf_1_val_4_ce0),
    .q0(k_buf_1_val_4_q0),
    .address1(k_buf_1_val_4_addr_reg_2553),
    .ce1(k_buf_1_val_4_ce1),
    .we1(k_buf_1_val_4_we1),
    .d1(k_buf_1_val_4_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_1_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_5_address0),
    .ce0(k_buf_1_val_5_ce0),
    .q0(k_buf_1_val_5_q0),
    .address1(k_buf_1_val_5_addr_reg_2559),
    .ce1(k_buf_1_val_5_ce1),
    .we1(k_buf_1_val_5_we1),
    .d1(k_buf_1_val_5_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_2_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_3_address0),
    .ce0(k_buf_2_val_3_ce0),
    .q0(k_buf_2_val_3_q0),
    .address1(k_buf_2_val_3_addr_reg_2565),
    .ce1(k_buf_2_val_3_ce1),
    .we1(k_buf_2_val_3_we1),
    .d1(p_src_data_stream_2_V_dout)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_2_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_4_address0),
    .ce0(k_buf_2_val_4_ce0),
    .q0(k_buf_2_val_4_q0),
    .address1(k_buf_2_val_4_addr_reg_2571),
    .ce1(k_buf_2_val_4_ce1),
    .we1(k_buf_2_val_4_we1),
    .d1(k_buf_2_val_4_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_2_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_5_address0),
    .ce0(k_buf_2_val_5_ce0),
    .q0(k_buf_2_val_5_q0),
    .address1(k_buf_2_val_5_addr_reg_2577),
    .ce1(k_buf_2_val_5_ce1),
    .we1(k_buf_2_val_5_we1),
    .d1(k_buf_2_val_5_d1)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U31(
    .din0(right_border_buf_0_s_fu_242),
    .din1(right_border_buf_0_1_fu_246),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1003_p2),
    .dout(tmp_26_fu_1008_p5)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U32(
    .din0(right_border_buf_0_2_fu_254),
    .din1(right_border_buf_0_3_fu_258),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1003_p2),
    .dout(tmp_27_fu_1027_p5)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U33(
    .din0(right_border_buf_0_4_fu_266),
    .din1(right_border_buf_0_5_fu_270),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1003_p2),
    .dout(tmp_28_fu_1046_p5)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U34(
    .din0(col_buf_0_val_0_0_fu_1020_p3),
    .din1(col_buf_0_val_1_0_fu_1039_p3),
    .din2(col_buf_0_val_2_0_fu_1058_p3),
    .din3(row_assign_9_0_0_t_reg_2473),
    .dout(tmp_29_fu_1104_p5)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U35(
    .din0(col_buf_0_val_0_0_fu_1020_p3),
    .din1(col_buf_0_val_1_0_fu_1039_p3),
    .din2(col_buf_0_val_2_0_fu_1058_p3),
    .din3(row_assign_9_0_1_t_reg_2480),
    .dout(tmp_33_fu_1122_p5)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U36(
    .din0(col_buf_0_val_0_0_fu_1020_p3),
    .din1(col_buf_0_val_1_0_fu_1039_p3),
    .din2(col_buf_0_val_2_0_fu_1058_p3),
    .din3(row_assign_9_0_2_t_reg_2487),
    .dout(tmp_37_fu_1140_p5)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U37(
    .din0(right_border_buf_1_s_fu_278),
    .din1(right_border_buf_1_1_fu_282),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1003_p2),
    .dout(tmp_44_fu_1279_p5)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U38(
    .din0(right_border_buf_1_2_fu_290),
    .din1(right_border_buf_1_3_fu_294),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1003_p2),
    .dout(tmp_45_fu_1298_p5)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U39(
    .din0(right_border_buf_1_4_fu_302),
    .din1(right_border_buf_1_5_fu_306),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1003_p2),
    .dout(tmp_46_fu_1317_p5)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U40(
    .din0(col_buf_1_val_0_0_fu_1291_p3),
    .din1(col_buf_1_val_1_0_fu_1310_p3),
    .din2(col_buf_1_val_2_0_fu_1329_p3),
    .din3(row_assign_9_0_0_t_reg_2473),
    .dout(tmp_47_fu_1375_p5)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U41(
    .din0(col_buf_1_val_0_0_fu_1291_p3),
    .din1(col_buf_1_val_1_0_fu_1310_p3),
    .din2(col_buf_1_val_2_0_fu_1329_p3),
    .din3(row_assign_9_0_1_t_reg_2480),
    .dout(tmp_48_fu_1393_p5)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U42(
    .din0(col_buf_1_val_0_0_fu_1291_p3),
    .din1(col_buf_1_val_1_0_fu_1310_p3),
    .din2(col_buf_1_val_2_0_fu_1329_p3),
    .din3(row_assign_9_0_2_t_reg_2487),
    .dout(tmp_49_fu_1411_p5)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U43(
    .din0(right_border_buf_2_5_fu_310),
    .din1(right_border_buf_2_4_fu_298),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1003_p2),
    .dout(tmp_56_fu_1541_p5)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U44(
    .din0(right_border_buf_2_3_fu_286),
    .din1(right_border_buf_2_2_fu_274),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1003_p2),
    .dout(tmp_57_fu_1560_p5)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U45(
    .din0(right_border_buf_2_1_fu_262),
    .din1(right_border_buf_2_s_fu_250),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1003_p2),
    .dout(tmp_58_fu_1579_p5)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U46(
    .din0(col_buf_2_val_0_0_fu_1553_p3),
    .din1(col_buf_2_val_1_0_fu_1572_p3),
    .din2(col_buf_2_val_2_0_fu_1591_p3),
    .din3(row_assign_9_0_0_t_reg_2473),
    .dout(tmp_59_fu_1628_p5)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U47(
    .din0(col_buf_2_val_0_0_fu_1553_p3),
    .din1(col_buf_2_val_1_0_fu_1572_p3),
    .din2(col_buf_2_val_2_0_fu_1591_p3),
    .din3(row_assign_9_0_1_t_reg_2480),
    .dout(tmp_60_fu_1646_p5)
);

edge_detect_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
edge_detect_mux_3ncg_U48(
    .din0(col_buf_2_val_0_0_fu_1553_p3),
    .din1(col_buf_2_val_1_0_fu_1572_p3),
    .din2(col_buf_2_val_2_0_fu_1591_p3),
    .din3(row_assign_9_0_2_t_reg_2487),
    .dout(tmp_61_fu_1664_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond389_i_fu_835_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond390_i_fu_543_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter1_state5)) | ((exitcond390_i_fu_543_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter1_state5))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((exitcond390_i_fu_543_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_fu_835_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_2_reg_516 <= j_V_fu_841_p2;
    end else if (((exitcond390_i_fu_543_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        t_V_2_reg_516 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_fu_533_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_reg_505 <= 10'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        t_V_reg_505 <= i_V_reg_2433;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_5_reg_494 <= 2'd0;
    end else if (((tmp_7_fu_533_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_5_reg_494 <= tmp_6_fu_527_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_fu_835_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_2512 <= brmerge_fu_953_p2;
        k_buf_0_val_3_addr_reg_2525 <= tmp_25_fu_958_p1;
        k_buf_0_val_4_addr_reg_2531 <= tmp_25_fu_958_p1;
        k_buf_0_val_5_addr_reg_2537 <= tmp_25_fu_958_p1;
        k_buf_1_val_3_addr_reg_2547 <= tmp_25_fu_958_p1;
        k_buf_1_val_4_addr_reg_2553 <= tmp_25_fu_958_p1;
        k_buf_1_val_5_addr_reg_2559 <= tmp_25_fu_958_p1;
        k_buf_2_val_3_addr_reg_2565 <= tmp_25_fu_958_p1;
        k_buf_2_val_4_addr_reg_2571 <= tmp_25_fu_958_p1;
        k_buf_2_val_5_addr_reg_2577 <= tmp_25_fu_958_p1;
        or_cond_i_i_reg_2503 <= or_cond_i_i_fu_889_p2;
        or_cond_i_reg_2543 <= or_cond_i_fu_971_p2;
        tmp_50_reg_2507 <= tmp_50_fu_949_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond389_i_reg_2494 <= exitcond389_i_fu_835_p2;
        or_cond_i_reg_2543_pp0_iter1_reg <= or_cond_i_reg_2543;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_V_reg_2433 <= i_V_fu_549_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond390_i_fu_543_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_reg_2447 <= icmp_fu_577_p2;
        row_assign_9_0_0_t_reg_2473 <= row_assign_9_0_0_t_fu_749_p2;
        row_assign_9_0_1_t_reg_2480 <= row_assign_9_0_1_t_fu_787_p2;
        row_assign_9_0_2_t_reg_2487 <= row_assign_9_0_2_t_fu_825_p2;
        tmp_116_0_1_reg_2456 <= tmp_116_0_1_fu_589_p2;
        tmp_1_reg_2438 <= tmp_1_fu_555_p2;
        tmp_2_reg_2460 <= tmp_2_fu_595_p2;
        tmp_72_0_0_not_reg_2442 <= tmp_72_0_0_not_fu_561_p2;
        tmp_9_reg_2452 <= tmp_9_fu_583_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op222_read_state5 == 1'b1))) begin
        right_border_buf_0_1_fu_246 <= right_border_buf_0_s_fu_242;
        right_border_buf_0_2_fu_254 <= col_buf_0_val_1_0_fu_1039_p3;
        right_border_buf_0_3_fu_258 <= right_border_buf_0_2_fu_254;
        right_border_buf_0_4_fu_266 <= col_buf_0_val_2_0_fu_1058_p3;
        right_border_buf_0_5_fu_270 <= right_border_buf_0_4_fu_266;
        right_border_buf_0_s_fu_242 <= col_buf_0_val_0_0_fu_1020_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op286_read_state5 == 1'b1))) begin
        right_border_buf_1_1_fu_282 <= right_border_buf_1_s_fu_278;
        right_border_buf_1_2_fu_290 <= col_buf_1_val_1_0_fu_1310_p3;
        right_border_buf_1_3_fu_294 <= right_border_buf_1_2_fu_290;
        right_border_buf_1_4_fu_302 <= col_buf_1_val_2_0_fu_1329_p3;
        right_border_buf_1_5_fu_306 <= right_border_buf_1_4_fu_302;
        right_border_buf_1_s_fu_278 <= col_buf_1_val_0_0_fu_1291_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op344_read_state5 == 1'b1))) begin
        right_border_buf_2_1_fu_262 <= col_buf_2_val_2_0_fu_1591_p3;
        right_border_buf_2_2_fu_274 <= right_border_buf_2_3_fu_286;
        right_border_buf_2_3_fu_286 <= col_buf_2_val_1_0_fu_1572_p3;
        right_border_buf_2_4_fu_298 <= right_border_buf_2_5_fu_310;
        right_border_buf_2_5_fu_310 <= col_buf_2_val_0_0_fu_1553_p3;
        right_border_buf_2_s_fu_250 <= right_border_buf_2_1_fu_262;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_1_fu_174 <= src_kernel_win_0_va_fu_170;
        src_kernel_win_0_va_2_fu_178 <= src_kernel_win_0_va_7_fu_1133_p3;
        src_kernel_win_0_va_3_fu_182 <= src_kernel_win_0_va_2_fu_178;
        src_kernel_win_0_va_4_fu_186 <= src_kernel_win_0_va_8_fu_1151_p3;
        src_kernel_win_0_va_5_fu_190 <= src_kernel_win_0_va_4_fu_186;
        src_kernel_win_0_va_fu_170 <= src_kernel_win_0_va_6_fu_1115_p3;
        src_kernel_win_1_va_1_fu_198 <= src_kernel_win_1_va_fu_194;
        src_kernel_win_1_va_2_fu_202 <= src_kernel_win_1_va_7_fu_1404_p3;
        src_kernel_win_1_va_3_fu_206 <= src_kernel_win_1_va_2_fu_202;
        src_kernel_win_1_va_4_fu_210 <= src_kernel_win_1_va_8_fu_1422_p3;
        src_kernel_win_1_va_5_fu_214 <= src_kernel_win_1_va_4_fu_210;
        src_kernel_win_1_va_fu_194 <= src_kernel_win_1_va_6_fu_1386_p3;
        src_kernel_win_2_va_1_fu_222 <= src_kernel_win_2_va_fu_218;
        src_kernel_win_2_va_2_fu_226 <= src_kernel_win_2_va_10_fu_1657_p3;
        src_kernel_win_2_va_3_fu_230 <= src_kernel_win_2_va_2_fu_226;
        src_kernel_win_2_va_4_fu_234 <= src_kernel_win_2_va_11_fu_1675_p3;
        src_kernel_win_2_va_5_fu_238 <= src_kernel_win_2_va_4_fu_234;
        src_kernel_win_2_va_fu_218 <= src_kernel_win_2_va_9_fu_1639_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_2494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_7_reg_2583 <= src_kernel_win_0_va_7_fu_1133_p3;
        src_kernel_win_1_va_7_reg_2609 <= src_kernel_win_1_va_7_fu_1404_p3;
        src_kernel_win_2_va_10_reg_2635 <= src_kernel_win_2_va_10_fu_1657_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2543 == 1'd1) & (exitcond389_i_reg_2494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp10_reg_2615 <= tmp10_fu_1508_p2;
        tmp12_reg_2620 <= tmp12_fu_1514_p2;
        tmp13_reg_2625 <= tmp13_fu_1520_p2;
        tmp15_reg_2630 <= tmp15_fu_1526_p2;
        tmp18_reg_2641 <= tmp18_fu_1761_p2;
        tmp20_reg_2646 <= tmp20_fu_1767_p2;
        tmp21_reg_2651 <= tmp21_fu_1773_p2;
        tmp23_reg_2656 <= tmp23_fu_1779_p2;
        tmp2_reg_2589 <= tmp2_fu_1237_p2;
        tmp4_reg_2594 <= tmp4_fu_1243_p2;
        tmp5_reg_2599 <= tmp5_fu_1249_p2;
        tmp7_reg_2604 <= tmp7_fu_1255_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state5 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((exitcond390_i_fu_543_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond390_i_fu_543_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2452 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op222_read_state5 == 1'b1)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2452 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op222_read_state5 == 1'b1)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_116_0_1_reg_2456 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op222_read_state5 == 1'b1)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op222_read_state5 == 1'b1)) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if ((1'b1 == ap_condition_553)) begin
            k_buf_0_val_4_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_116_0_1_reg_2456 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op222_read_state5 == 1'b1)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2452 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op222_read_state5 == 1'b1)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op222_read_state5 == 1'b1)) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if ((1'b1 == ap_condition_547)) begin
            k_buf_0_val_5_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2452 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op222_read_state5 == 1'b1)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_3_ce0 = 1'b1;
    end else begin
        k_buf_1_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2452 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op286_read_state5 == 1'b1)))) begin
        k_buf_1_val_3_ce1 = 1'b1;
    end else begin
        k_buf_1_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2452 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op286_read_state5 == 1'b1)))) begin
        k_buf_1_val_3_we1 = 1'b1;
    end else begin
        k_buf_1_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_4_ce0 = 1'b1;
    end else begin
        k_buf_1_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_116_0_1_reg_2456 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op286_read_state5 == 1'b1)))) begin
        k_buf_1_val_4_ce1 = 1'b1;
    end else begin
        k_buf_1_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op286_read_state5 == 1'b1)) begin
            k_buf_1_val_4_d1 = k_buf_1_val_3_q0;
        end else if ((1'b1 == ap_condition_553)) begin
            k_buf_1_val_4_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_116_0_1_reg_2456 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op286_read_state5 == 1'b1)))) begin
        k_buf_1_val_4_we1 = 1'b1;
    end else begin
        k_buf_1_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_5_ce0 = 1'b1;
    end else begin
        k_buf_1_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2452 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op286_read_state5 == 1'b1)))) begin
        k_buf_1_val_5_ce1 = 1'b1;
    end else begin
        k_buf_1_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op286_read_state5 == 1'b1)) begin
            k_buf_1_val_5_d1 = k_buf_1_val_4_q0;
        end else if ((1'b1 == ap_condition_547)) begin
            k_buf_1_val_5_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2452 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op286_read_state5 == 1'b1)))) begin
        k_buf_1_val_5_we1 = 1'b1;
    end else begin
        k_buf_1_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_3_ce0 = 1'b1;
    end else begin
        k_buf_2_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2452 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op344_read_state5 == 1'b1)))) begin
        k_buf_2_val_3_ce1 = 1'b1;
    end else begin
        k_buf_2_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2452 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op344_read_state5 == 1'b1)))) begin
        k_buf_2_val_3_we1 = 1'b1;
    end else begin
        k_buf_2_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_4_ce0 = 1'b1;
    end else begin
        k_buf_2_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_116_0_1_reg_2456 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op344_read_state5 == 1'b1)))) begin
        k_buf_2_val_4_ce1 = 1'b1;
    end else begin
        k_buf_2_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op344_read_state5 == 1'b1)) begin
            k_buf_2_val_4_d1 = k_buf_2_val_3_q0;
        end else if ((1'b1 == ap_condition_553)) begin
            k_buf_2_val_4_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_116_0_1_reg_2456 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op344_read_state5 == 1'b1)))) begin
        k_buf_2_val_4_we1 = 1'b1;
    end else begin
        k_buf_2_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_5_ce0 = 1'b1;
    end else begin
        k_buf_2_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2452 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op344_read_state5 == 1'b1)))) begin
        k_buf_2_val_5_ce1 = 1'b1;
    end else begin
        k_buf_2_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op344_read_state5 == 1'b1)) begin
            k_buf_2_val_5_d1 = k_buf_2_val_4_q0;
        end else if ((1'b1 == ap_condition_547)) begin
            k_buf_2_val_5_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2452 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op344_read_state5 == 1'b1)))) begin
        k_buf_2_val_5_we1 = 1'b1;
    end else begin
        k_buf_2_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n;
    end else begin
        p_dst_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_0_V_write = 1'b1;
    end else begin
        p_dst_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n;
    end else begin
        p_dst_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_1_V_write = 1'b1;
    end else begin
        p_dst_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_dst_data_stream_2_V_blk_n = p_dst_data_stream_2_V_full_n;
    end else begin
        p_dst_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_2_V_write = 1'b1;
    end else begin
        p_dst_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_1_reg_2438 == 1'd1) & (icmp_reg_2447 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (exitcond389_i_reg_2494 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n;
    end else begin
        p_src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op222_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op210_read_state5 == 1'b1)))) begin
        p_src_data_stream_0_V_read = 1'b1;
    end else begin
        p_src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_1_reg_2438 == 1'd1) & (icmp_reg_2447 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (exitcond389_i_reg_2494 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n;
    end else begin
        p_src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op286_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op274_read_state5 == 1'b1)))) begin
        p_src_data_stream_1_V_read = 1'b1;
    end else begin
        p_src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_1_reg_2438 == 1'd1) & (icmp_reg_2447 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (exitcond389_i_reg_2494 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n;
    end else begin
        p_src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op344_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op335_read_state5 == 1'b1)))) begin
        p_src_data_stream_2_V_read = 1'b1;
    end else begin
        p_src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_7_fu_533_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond390_i_fu_543_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_863_p2 = ($signed(12'd4095) + $signed(t_V_2_cast_fu_831_p1));

assign OP1_V_0_0_cast_fu_1167_p1 = src_kernel_win_0_va_5_fu_190;

assign OP1_V_0_2_cast_fu_1215_p1 = src_kernel_win_0_va_1_fu_174;

assign OP1_V_1_0_cast_fu_1438_p1 = src_kernel_win_1_va_5_fu_214;

assign OP1_V_1_2_cast_fu_1486_p1 = src_kernel_win_1_va_1_fu_198;

assign OP1_V_2_0_cast_fu_1691_p1 = src_kernel_win_2_va_5_fu_238;

assign OP1_V_2_2_cast_fu_1739_p1 = src_kernel_win_2_va_1_fu_222;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op344_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op335_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op286_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op274_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op222_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op210_read_state5 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op344_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op335_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op286_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op274_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op222_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op210_read_state5 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op344_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op335_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op286_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op274_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op222_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op210_read_state5 == 1'b1)))));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op344_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op335_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op286_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op274_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op222_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op210_read_state5 == 1'b1)));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter2 = (((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2543_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_547 = ((tmp_9_reg_2452 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0));
end

always @ (*) begin
    ap_condition_553 = ((tmp_116_0_1_reg_2456 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0));
end

always @ (*) begin
    ap_condition_62 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op210_read_state5 = ((or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0));
end

always @ (*) begin
    ap_predicate_op222_read_state5 = ((tmp_1_reg_2438 == 1'd1) & (icmp_reg_2447 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (exitcond389_i_reg_2494 == 1'd0));
end

always @ (*) begin
    ap_predicate_op274_read_state5 = ((or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0));
end

always @ (*) begin
    ap_predicate_op286_read_state5 = ((tmp_1_reg_2438 == 1'd1) & (icmp_reg_2447 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (exitcond389_i_reg_2494 == 1'd0));
end

always @ (*) begin
    ap_predicate_op335_read_state5 = ((or_cond_i_i_reg_2503 == 1'd1) & (icmp_reg_2447 == 1'd0) & (exitcond389_i_reg_2494 == 1'd0));
end

always @ (*) begin
    ap_predicate_op344_read_state5 = ((tmp_1_reg_2438 == 1'd1) & (icmp_reg_2447 == 1'd1) & (or_cond_i_i_reg_2503 == 1'd1) & (exitcond389_i_reg_2494 == 1'd0));
end

assign brmerge_fu_953_p2 = (tmp_72_0_0_not_reg_2442 | tmp_21_fu_883_p2);

assign col_assign_2_0_t_fu_1003_p2 = (tmp_50_reg_2507 ^ 2'd3);

assign col_buf_0_val_0_0_fu_1020_p3 = ((brmerge_reg_2512[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_26_fu_1008_p5);

assign col_buf_0_val_1_0_fu_1039_p3 = ((brmerge_reg_2512[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_27_fu_1027_p5);

assign col_buf_0_val_2_0_fu_1058_p3 = ((brmerge_reg_2512[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_28_fu_1046_p5);

assign col_buf_1_val_0_0_fu_1291_p3 = ((brmerge_reg_2512[0:0] === 1'b1) ? k_buf_1_val_3_q0 : tmp_44_fu_1279_p5);

assign col_buf_1_val_1_0_fu_1310_p3 = ((brmerge_reg_2512[0:0] === 1'b1) ? k_buf_1_val_4_q0 : tmp_45_fu_1298_p5);

assign col_buf_1_val_2_0_fu_1329_p3 = ((brmerge_reg_2512[0:0] === 1'b1) ? k_buf_1_val_5_q0 : tmp_46_fu_1317_p5);

assign col_buf_2_val_0_0_fu_1553_p3 = ((brmerge_reg_2512[0:0] === 1'b1) ? k_buf_2_val_3_q0 : tmp_56_fu_1541_p5);

assign col_buf_2_val_1_0_fu_1572_p3 = ((brmerge_reg_2512[0:0] === 1'b1) ? k_buf_2_val_4_q0 : tmp_57_fu_1560_p5);

assign col_buf_2_val_2_0_fu_1591_p3 = ((brmerge_reg_2512[0:0] === 1'b1) ? k_buf_2_val_5_q0 : tmp_58_fu_1579_p5);

assign exitcond389_i_fu_835_p2 = ((t_V_2_reg_516 == 11'd1282) ? 1'b1 : 1'b0);

assign exitcond390_i_fu_543_p2 = ((t_V_reg_505 == 10'd722) ? 1'b1 : 1'b0);

assign i_V_fu_549_p2 = (t_V_reg_505 + 10'd1);

assign icmp1_fu_857_p2 = ((tmp_40_fu_847_p4 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_fu_577_p2 = ((tmp_fu_567_p4 != 9'd0) ? 1'b1 : 1'b0);

assign isneg_1_fu_2031_p3 = p_Val2_5_fu_2026_p2[32'd10];

assign isneg_2_fu_2130_p3 = p_Val2_s_fu_2125_p2[32'd10];

assign isneg_fu_1932_p3 = p_Val2_2_fu_1927_p2[32'd10];

assign j_V_fu_841_p2 = (t_V_2_reg_516 + 11'd1);

assign k_buf_0_val_3_address0 = tmp_25_fu_958_p1;

assign k_buf_0_val_4_address0 = tmp_25_fu_958_p1;

assign k_buf_0_val_5_address0 = tmp_25_fu_958_p1;

assign k_buf_1_val_3_address0 = tmp_25_fu_958_p1;

assign k_buf_1_val_4_address0 = tmp_25_fu_958_p1;

assign k_buf_1_val_5_address0 = tmp_25_fu_958_p1;

assign k_buf_2_val_3_address0 = tmp_25_fu_958_p1;

assign k_buf_2_val_4_address0 = tmp_25_fu_958_p1;

assign k_buf_2_val_5_address0 = tmp_25_fu_958_p1;

assign not_i_i_i1_fu_2065_p2 = ((tmp_54_fu_2049_p4 != 3'd0) ? 1'b1 : 1'b0);

assign not_i_i_i2_fu_2164_p2 = ((tmp_64_fu_2148_p4 != 3'd0) ? 1'b1 : 1'b0);

assign not_i_i_i_fu_1966_p2 = ((tmp_42_fu_1950_p4 != 3'd0) ? 1'b1 : 1'b0);

assign or_cond_i425_i_fu_637_p2 = (tmp_4_fu_631_p2 & rev_fu_625_p2);

assign or_cond_i_fu_971_p2 = (icmp_reg_2447 & icmp1_fu_857_p2);

assign or_cond_i_i_fu_889_p2 = (tmp_21_fu_883_p2 & rev1_fu_877_p2);

assign overflow_1_fu_2071_p2 = (tmp_i_i1_fu_2059_p2 & not_i_i_i1_fu_2065_p2);

assign overflow_2_fu_2170_p2 = (tmp_i_i2_fu_2158_p2 & not_i_i_i2_fu_2164_p2);

assign overflow_fu_1972_p2 = (tmp_i_i_fu_1960_p2 & not_i_i_i_fu_1966_p2);

assign p_Val2_10_0_0_2_ca_fu_1181_p1 = p_Val2_10_0_0_2_fu_1175_p2;

assign p_Val2_10_0_0_2_fu_1175_p2 = (tmp_160_0_0_2_cast_fu_1171_p1 - OP1_V_0_0_cast_fu_1167_p1);

assign p_Val2_10_1_0_2_ca_fu_1452_p1 = p_Val2_10_1_0_2_fu_1446_p2;

assign p_Val2_10_1_0_2_fu_1446_p2 = (tmp_160_1_0_2_cast_fu_1442_p1 - OP1_V_1_0_cast_fu_1438_p1);

assign p_Val2_10_2_0_2_ca_fu_1705_p1 = p_Val2_10_2_0_2_fu_1699_p2;

assign p_Val2_10_2_0_2_fu_1699_p2 = (tmp_160_2_0_2_cast_fu_1695_p1 - OP1_V_2_0_cast_fu_1691_p1);

assign p_Val2_1_fu_1945_p2 = (tmp5_reg_2599 + tmp6_fu_1940_p2);

assign p_Val2_2_fu_1927_p2 = (tmp2_reg_2589 + tmp3_fu_1921_p2);

assign p_Val2_3_fu_2044_p2 = (tmp13_reg_2625 + tmp14_fu_2039_p2);

assign p_Val2_5_fu_2026_p2 = (tmp10_reg_2615 + tmp11_fu_2020_p2);

assign p_Val2_6_fu_2143_p2 = (tmp21_reg_2651 + tmp22_fu_2138_p2);

assign p_Val2_s_fu_2125_p2 = (tmp18_reg_2641 + tmp19_fu_2119_p2);

assign p_assign_1_fu_903_p2 = (12'd1 - t_V_2_cast_fu_831_p1);

assign p_assign_2_fu_923_p2 = ($signed(12'd2558) - $signed(p_p2_i_i_fu_909_p3));

assign p_assign_6_0_1_fu_681_p2 = ($signed(11'd2046) + $signed(t_V_cast_fu_539_p1));

assign p_assign_6_0_2_fu_707_p2 = ($signed(11'd2045) + $signed(t_V_cast_fu_539_p1));

assign p_assign_7_fu_651_p2 = (11'd1 - t_V_cast_fu_539_p1);

assign p_assign_8_fu_675_p2 = ($signed(2'd2) - $signed(tmp_12_fu_665_p1));

assign p_dst_data_stream_0_V_din = ((tmp_i_i_65_fu_1986_p2[0:0] === 1'b1) ? p_mux_i_i_cast_fu_1978_p3 : p_Val2_1_fu_1945_p2);

assign p_dst_data_stream_1_V_din = ((tmp_i_i1_67_fu_2085_p2[0:0] === 1'b1) ? p_mux_i_i30_cast_fu_2077_p3 : p_Val2_3_fu_2044_p2);

assign p_dst_data_stream_2_V_din = ((tmp_i_i2_69_fu_2184_p2[0:0] === 1'b1) ? p_mux_i_i39_cast_fu_2176_p3 : p_Val2_6_fu_2143_p2);

assign p_mux_i_i30_cast_fu_2077_p3 = ((tmp_i_i1_fu_2059_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i39_cast_fu_2176_p3 = ((tmp_i_i2_fu_2158_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i_cast_fu_1978_p3 = ((tmp_i_i_fu_1960_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_p2_i426_i_0_p_assig_fu_733_p3 = ((tmp_13_fu_669_p2[0:0] === 1'b1) ? tmp_12_fu_665_p1 : p_assign_8_fu_675_p2);

assign p_p2_i426_i_fu_657_p3 = ((tmp_11_fu_643_p3[0:0] === 1'b1) ? p_assign_7_fu_651_p2 : tmp_3_fu_605_p2);

assign p_p2_i_i_fu_909_p3 = ((tmp_43_fu_895_p3[0:0] === 1'b1) ? p_assign_1_fu_903_p2 : ImagLoc_x_fu_863_p2);

assign p_p2_i_i_p_assign_2_fu_929_p3 = ((tmp_23_fu_917_p2[0:0] === 1'b1) ? p_p2_i_i_fu_909_p3 : p_assign_2_fu_923_p2);

assign p_shl1_cast_fu_1464_p1 = p_shl1_fu_1456_p3;

assign p_shl1_fu_1456_p3 = {{src_kernel_win_1_va_3_fu_206}, {1'd0}};

assign p_shl2_cast_fu_1717_p1 = p_shl2_fu_1709_p3;

assign p_shl2_fu_1709_p3 = {{src_kernel_win_2_va_3_fu_230}, {1'd0}};

assign p_shl_cast_fu_1193_p1 = p_shl_fu_1185_p3;

assign p_shl_fu_1185_p3 = {{src_kernel_win_0_va_3_fu_182}, {1'd0}};

assign r_V_7_0_1_2_fu_1902_p3 = {{src_kernel_win_0_va_7_reg_2583}, {1'd0}};

assign r_V_7_0_1_fu_1197_p2 = (10'd0 - p_shl_cast_fu_1193_p1);

assign r_V_7_0_2_fu_1219_p2 = (9'd0 - OP1_V_0_2_cast_fu_1215_p1);

assign r_V_7_1_1_2_fu_2001_p3 = {{src_kernel_win_1_va_7_reg_2609}, {1'd0}};

assign r_V_7_1_1_fu_1468_p2 = (10'd0 - p_shl1_cast_fu_1464_p1);

assign r_V_7_1_2_fu_1490_p2 = (9'd0 - OP1_V_1_2_cast_fu_1486_p1);

assign r_V_7_2_1_2_fu_2100_p3 = {{src_kernel_win_2_va_10_reg_2635}, {1'd0}};

assign r_V_7_2_1_fu_1721_p2 = (10'd0 - p_shl2_cast_fu_1717_p1);

assign r_V_7_2_2_fu_1743_p2 = (9'd0 - OP1_V_2_2_cast_fu_1739_p1);

assign rev1_fu_877_p2 = (tmp_41_fu_869_p3 ^ 1'd1);

assign rev_fu_625_p2 = (tmp_10_fu_617_p3 ^ 1'd1);

assign row_assign_9_0_0_t_fu_749_p2 = (y_1_fu_741_p3 ^ 2'd3);

assign row_assign_9_0_1_t_fu_787_p2 = (tmp_32_fu_779_p3 ^ 2'd3);

assign row_assign_9_0_2_t_fu_825_p2 = (tmp_36_fu_817_p3 ^ 2'd3);

assign src_kernel_win_0_va_6_fu_1115_p3 = ((tmp_2_reg_2460[0:0] === 1'b1) ? tmp_29_fu_1104_p5 : col_buf_0_val_0_0_fu_1020_p3);

assign src_kernel_win_0_va_7_fu_1133_p3 = ((tmp_2_reg_2460[0:0] === 1'b1) ? tmp_33_fu_1122_p5 : col_buf_0_val_1_0_fu_1039_p3);

assign src_kernel_win_0_va_8_fu_1151_p3 = ((tmp_2_reg_2460[0:0] === 1'b1) ? tmp_37_fu_1140_p5 : col_buf_0_val_2_0_fu_1058_p3);

assign src_kernel_win_1_va_6_fu_1386_p3 = ((tmp_2_reg_2460[0:0] === 1'b1) ? tmp_47_fu_1375_p5 : col_buf_1_val_0_0_fu_1291_p3);

assign src_kernel_win_1_va_7_fu_1404_p3 = ((tmp_2_reg_2460[0:0] === 1'b1) ? tmp_48_fu_1393_p5 : col_buf_1_val_1_0_fu_1310_p3);

assign src_kernel_win_1_va_8_fu_1422_p3 = ((tmp_2_reg_2460[0:0] === 1'b1) ? tmp_49_fu_1411_p5 : col_buf_1_val_2_0_fu_1329_p3);

assign src_kernel_win_2_va_10_fu_1657_p3 = ((tmp_2_reg_2460[0:0] === 1'b1) ? tmp_60_fu_1646_p5 : col_buf_2_val_1_0_fu_1572_p3);

assign src_kernel_win_2_va_11_fu_1675_p3 = ((tmp_2_reg_2460[0:0] === 1'b1) ? tmp_61_fu_1664_p5 : col_buf_2_val_2_0_fu_1591_p3);

assign src_kernel_win_2_va_9_fu_1639_p3 = ((tmp_2_reg_2460[0:0] === 1'b1) ? tmp_59_fu_1628_p5 : col_buf_2_val_0_0_fu_1553_p3);

assign t_V_2_cast_fu_831_p1 = t_V_2_reg_516;

assign t_V_cast_fu_539_p1 = t_V_reg_505;

assign tmp10_fu_1508_p2 = ($signed(tmp_160_1_2_cast_fu_1496_p1) + $signed(tmp_160_1_1_cast_fu_1474_p1));

assign tmp11_fu_2020_p2 = ($signed(tmp_160_1_1_cast_66_fu_2008_p1) + $signed(tmp12_cast_fu_2017_p1));

assign tmp12_cast_fu_2017_p1 = $signed(tmp12_reg_2620);

assign tmp12_fu_1514_p2 = ($signed(tmp_160_1_2_2_cast_c_fu_1504_p1) + $signed(p_Val2_10_1_0_2_ca_fu_1452_p1));

assign tmp13_fu_1520_p2 = (tmp_70_fu_1482_p1 + tmp_69_fu_1478_p1);

assign tmp14_fu_2039_p2 = (tmp_71_fu_2012_p2 + tmp15_reg_2630);

assign tmp15_fu_1526_p2 = (src_kernel_win_1_va_6_fu_1386_p3 + tmp_72_fu_1500_p1);

assign tmp18_fu_1761_p2 = ($signed(tmp_160_2_2_cast_fu_1749_p1) + $signed(tmp_160_2_1_cast_fu_1727_p1));

assign tmp19_fu_2119_p2 = ($signed(tmp_160_2_1_cast_68_fu_2107_p1) + $signed(tmp20_cast_fu_2116_p1));

assign tmp20_cast_fu_2116_p1 = $signed(tmp20_reg_2646);

assign tmp20_fu_1767_p2 = ($signed(tmp_160_2_2_2_cast_c_fu_1757_p1) + $signed(p_Val2_10_2_0_2_ca_fu_1705_p1));

assign tmp21_fu_1773_p2 = (tmp_78_fu_1735_p1 + tmp_77_fu_1731_p1);

assign tmp22_fu_2138_p2 = (tmp_79_fu_2111_p2 + tmp23_reg_2656);

assign tmp23_fu_1779_p2 = (src_kernel_win_2_va_9_fu_1639_p3 + tmp_80_fu_1753_p1);

assign tmp2_fu_1237_p2 = ($signed(tmp_160_0_2_cast_fu_1225_p1) + $signed(tmp_160_0_1_cast_fu_1203_p1));

assign tmp3_fu_1921_p2 = ($signed(tmp_160_0_1_cast_64_fu_1909_p1) + $signed(tmp4_cast_fu_1918_p1));

assign tmp4_cast_fu_1918_p1 = $signed(tmp4_reg_2594);

assign tmp4_fu_1243_p2 = ($signed(tmp_160_0_2_2_cast_c_fu_1233_p1) + $signed(p_Val2_10_0_0_2_ca_fu_1181_p1));

assign tmp5_fu_1249_p2 = (tmp_55_fu_1211_p1 + tmp_53_fu_1207_p1);

assign tmp6_fu_1940_p2 = (tmp_62_fu_1913_p2 + tmp7_reg_2604);

assign tmp7_fu_1255_p2 = (src_kernel_win_0_va_6_fu_1115_p3 + tmp_63_fu_1229_p1);

assign tmp_10_fu_617_p3 = tmp_3_fu_605_p2[32'd10];

assign tmp_116_0_1_fu_589_p2 = ((t_V_reg_505 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_11_fu_643_p3 = tmp_3_fu_605_p2[32'd10];

assign tmp_12_fu_665_p1 = p_p2_i426_i_fu_657_p3[1:0];

assign tmp_13_fu_669_p2 = (($signed(p_p2_i426_i_fu_657_p3) < $signed(11'd720)) ? 1'b1 : 1'b0);

assign tmp_140_cast_fu_611_p2 = ($signed(2'd3) + $signed(tmp_8_fu_601_p1));

assign tmp_14_fu_687_p3 = p_assign_6_0_1_fu_681_p2[32'd10];

assign tmp_15_fu_695_p3 = p_assign_6_0_1_fu_681_p2[32'd10];

assign tmp_160_0_0_2_cast_fu_1171_p1 = src_kernel_win_0_va_8_fu_1151_p3;

assign tmp_160_0_1_cast_64_fu_1909_p1 = r_V_7_0_1_2_fu_1902_p3;

assign tmp_160_0_1_cast_fu_1203_p1 = r_V_7_0_1_fu_1197_p2;

assign tmp_160_0_2_2_cast_c_fu_1233_p1 = src_kernel_win_0_va_6_fu_1115_p3;

assign tmp_160_0_2_cast_fu_1225_p1 = r_V_7_0_2_fu_1219_p2;

assign tmp_160_1_0_2_cast_fu_1442_p1 = src_kernel_win_1_va_8_fu_1422_p3;

assign tmp_160_1_1_cast_66_fu_2008_p1 = r_V_7_1_1_2_fu_2001_p3;

assign tmp_160_1_1_cast_fu_1474_p1 = r_V_7_1_1_fu_1468_p2;

assign tmp_160_1_2_2_cast_c_fu_1504_p1 = src_kernel_win_1_va_6_fu_1386_p3;

assign tmp_160_1_2_cast_fu_1496_p1 = r_V_7_1_2_fu_1490_p2;

assign tmp_160_2_0_2_cast_fu_1695_p1 = src_kernel_win_2_va_11_fu_1675_p3;

assign tmp_160_2_1_cast_68_fu_2107_p1 = r_V_7_2_1_2_fu_2100_p3;

assign tmp_160_2_1_cast_fu_1727_p1 = r_V_7_2_1_fu_1721_p2;

assign tmp_160_2_2_2_cast_c_fu_1757_p1 = src_kernel_win_2_va_9_fu_1639_p3;

assign tmp_160_2_2_cast_fu_1749_p1 = r_V_7_2_2_fu_1743_p2;

assign tmp_16_fu_755_p2 = (tmp_8_fu_601_p1 ^ 2'd2);

assign tmp_17_fu_703_p1 = t_V_reg_505[1:0];

assign tmp_19_fu_713_p3 = p_assign_6_0_2_fu_707_p2[32'd10];

assign tmp_1_fu_555_p2 = ((t_V_reg_505 < 10'd720) ? 1'b1 : 1'b0);

assign tmp_20_fu_721_p3 = p_assign_6_0_2_fu_707_p2[32'd10];

assign tmp_21_fu_883_p2 = (($signed(ImagLoc_x_fu_863_p2) < $signed(12'd1280)) ? 1'b1 : 1'b0);

assign tmp_22_fu_729_p1 = t_V_reg_505[1:0];

assign tmp_23_fu_917_p2 = (($signed(p_p2_i_i_fu_909_p3) < $signed(12'd1280)) ? 1'b1 : 1'b0);

assign tmp_24_fu_761_p2 = ($signed(2'd2) - $signed(tmp_17_fu_703_p1));

assign tmp_25_fu_958_p1 = $unsigned(x_cast_fu_945_p1);

assign tmp_2_fu_595_p2 = ((t_V_reg_505 > 10'd720) ? 1'b1 : 1'b0);

assign tmp_30_fu_767_p1 = p_assign_6_0_1_fu_681_p2[1:0];

assign tmp_31_fu_771_p3 = ((tmp_15_fu_695_p3[0:0] === 1'b1) ? tmp_24_fu_761_p2 : tmp_30_fu_767_p1);

assign tmp_32_fu_779_p3 = ((tmp_14_fu_687_p3[0:0] === 1'b1) ? tmp_31_fu_771_p3 : tmp_16_fu_755_p2);

assign tmp_34_fu_793_p2 = (2'd1 + tmp_8_fu_601_p1);

assign tmp_35_fu_799_p2 = (tmp_22_fu_729_p1 ^ 2'd3);

assign tmp_36_fu_817_p3 = ((tmp_19_fu_713_p3[0:0] === 1'b1) ? tmp_39_fu_809_p3 : tmp_34_fu_793_p2);

assign tmp_38_fu_805_p1 = p_assign_6_0_2_fu_707_p2[1:0];

assign tmp_39_fu_809_p3 = ((tmp_20_fu_721_p3[0:0] === 1'b1) ? tmp_35_fu_799_p2 : tmp_38_fu_805_p1);

assign tmp_3_fu_605_p2 = ($signed(11'd2047) + $signed(t_V_cast_fu_539_p1));

assign tmp_40_fu_847_p4 = {{t_V_2_reg_516[10:1]}};

assign tmp_41_fu_869_p3 = ImagLoc_x_fu_863_p2[32'd11];

assign tmp_42_fu_1950_p4 = {{p_Val2_2_fu_1927_p2[10:8]}};

assign tmp_43_fu_895_p3 = ImagLoc_x_fu_863_p2[32'd11];

assign tmp_4_fu_631_p2 = (($signed(tmp_3_fu_605_p2) < $signed(11'd720)) ? 1'b1 : 1'b0);

assign tmp_50_fu_949_p1 = x_fu_937_p3[1:0];

assign tmp_53_fu_1207_p1 = p_Val2_10_0_0_2_fu_1175_p2[7:0];

assign tmp_54_fu_2049_p4 = {{p_Val2_5_fu_2026_p2[10:8]}};

assign tmp_55_fu_1211_p1 = r_V_7_0_1_fu_1197_p2[7:0];

assign tmp_62_fu_1913_p2 = src_kernel_win_0_va_7_reg_2583 << 8'd1;

assign tmp_63_fu_1229_p1 = r_V_7_0_2_fu_1219_p2[7:0];

assign tmp_64_fu_2148_p4 = {{p_Val2_s_fu_2125_p2[10:8]}};

assign tmp_69_fu_1478_p1 = p_Val2_10_1_0_2_fu_1446_p2[7:0];

assign tmp_6_fu_527_p2 = (tmp_5_reg_494 + 2'd1);

assign tmp_70_fu_1482_p1 = r_V_7_1_1_fu_1468_p2[7:0];

assign tmp_71_fu_2012_p2 = src_kernel_win_1_va_7_reg_2609 << 8'd1;

assign tmp_72_0_0_not_fu_561_p2 = (tmp_1_fu_555_p2 ^ 1'd1);

assign tmp_72_fu_1500_p1 = r_V_7_1_2_fu_1490_p2[7:0];

assign tmp_77_fu_1731_p1 = p_Val2_10_2_0_2_fu_1699_p2[7:0];

assign tmp_78_fu_1735_p1 = r_V_7_2_1_fu_1721_p2[7:0];

assign tmp_79_fu_2111_p2 = src_kernel_win_2_va_10_reg_2635 << 8'd1;

assign tmp_7_fu_533_p2 = ((tmp_5_reg_494 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_80_fu_1753_p1 = r_V_7_2_2_fu_1743_p2[7:0];

assign tmp_8_fu_601_p1 = t_V_reg_505[1:0];

assign tmp_9_fu_583_p2 = ((t_V_reg_505 == 10'd1) ? 1'b1 : 1'b0);

assign tmp_fu_567_p4 = {{t_V_reg_505[9:1]}};

assign tmp_i_i1_67_fu_2085_p2 = (overflow_1_fu_2071_p2 | isneg_1_fu_2031_p3);

assign tmp_i_i1_fu_2059_p2 = (isneg_1_fu_2031_p3 ^ 1'd1);

assign tmp_i_i2_69_fu_2184_p2 = (overflow_2_fu_2170_p2 | isneg_2_fu_2130_p3);

assign tmp_i_i2_fu_2158_p2 = (isneg_2_fu_2130_p3 ^ 1'd1);

assign tmp_i_i_65_fu_1986_p2 = (overflow_fu_1972_p2 | isneg_fu_1932_p3);

assign tmp_i_i_fu_1960_p2 = (isneg_fu_1932_p3 ^ 1'd1);

assign x_cast_fu_945_p1 = x_fu_937_p3;

assign x_fu_937_p3 = ((or_cond_i_i_fu_889_p2[0:0] === 1'b1) ? ImagLoc_x_fu_863_p2 : p_p2_i_i_p_assign_2_fu_929_p3);

assign y_1_fu_741_p3 = ((or_cond_i425_i_fu_637_p2[0:0] === 1'b1) ? tmp_140_cast_fu_611_p2 : p_p2_i426_i_0_p_assig_fu_733_p3);

endmodule //Filter2D
