# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/41ae117b-7960-45f9-925c-acf598b79618/tpg_vdma.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/design_1_v_tpg_0_0.xci
# IP: The module: 'design_1_v_tpg_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/41ae117b-7960-45f9-925c-acf598b79618/tpg_vdma.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/design_1_v_tpg_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /mnt/41ae117b-7960-45f9-925c-acf598b79618/tpg_vdma.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/design_1_v_tpg_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /mnt/41ae117b-7960-45f9-925c-acf598b79618/tpg_vdma.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/design_1_v_tpg_0_0.xci
# IP: The module: 'design_1_v_tpg_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/41ae117b-7960-45f9-925c-acf598b79618/tpg_vdma.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/design_1_v_tpg_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /mnt/41ae117b-7960-45f9-925c-acf598b79618/tpg_vdma.srcs/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/design_1_v_tpg_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
